name: "Cloudfront Invalidator"
description: "Invalidate cloudfront cache"
inputs:
  tag_key:
    description: "Cloudfront Distribution tag name"
    required: true
  tag_value:
    description: "Cloudfront Distribution tag value"
    required: true
  paths:
    description: 'Path to invalidate e.q. "/example/*, /index.html"'
    required: true
  wait:
    description: "Wait for the invalidation to complete"
    required: false
    default: "true"
  timeout:
    description: "Maximum wait time in seconds"
    required: false
    default: "600"
runs:
  using: node20
  main: dist/index.js
